# Generated by Django 4.1.5 on 2023-01-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('S', 'Started'), ('F', 'Finished'), ('T', 'To Read')], default='T', max_length=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('current_page', models.PositiveIntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, choices=[(0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5')], decimal_places=1, default=0.0, max_digits=2)),
                ('likes', models.TextField(blank=True, help_text='What did you like about the book?')),
                ('dislikes', models.TextField(blank=True, help_text='What did you dislike about the book?')),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bookshelf')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
