# Generated by Django 4.1.5 on 2023-02-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_book_book_book_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='bookshelf',
        ),
    ]
