# Generated by Django 4.1.5 on 2023-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_bookshelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.ManyToManyField(related_name='book_set', to='main.bookshelf'),
        ),
    ]
