# Generated by Django 4.1.5 on 2023-11-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_book_bookshelf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-finish_date']},
        ),
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
    ]
