# Generated by Django 4.1.5 on 2024-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_book_options_alter_bookshelf_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='editable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
